// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// polar2cartesian
Rcpp::NumericMatrix polar2cartesian(arma::vec r, arma::vec theta);
RcppExport SEXP sccm_polar2cartesian(SEXP rSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(polar2cartesian(r, theta));
    return rcpp_result_gen;
END_RCPP
}
// cartesian2polar
Rcpp::NumericMatrix cartesian2polar(arma::vec x, arma::vec y);
RcppExport SEXP sccm_cartesian2polar(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cartesian2polar(x, y));
    return rcpp_result_gen;
END_RCPP
}
// convex_hull_cpp
Rcpp::List convex_hull_cpp(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP sccm_convex_hull_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(convex_hull_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// polygon_cpp
Rcpp::List polygon_cpp(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP sccm_polygon_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(polygon_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
