# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' convexHull
#'
#' return the convex hull for a set of (x, y) points
#'
#' @param x a numeric vector of x coordinates
#' @param y a numeric vector of y coordinates
#' 
#' @return a matrix, the convex hull vertices listed in an anti-clockwise
#' order.
#'
#' @export
convex_hull <- function(x, y) {
    .Call('sccm_convex_hull', PACKAGE = 'sccm', x, y)
}

