# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Translate between Polar and Cartesian Coordinates.
#'
#' Given (x,y) return (r, theta), or visa-versa.
#'
#' @param r a numeric vector of radii
#' @param theta a numeric vector of angles (in radians)
#' @export
#' @rdname polar2cartesian
polar2cartesian <- function(r, theta) {
    .Call('_sccm_polar2cartesian', PACKAGE = 'sccm', r, theta)
}

#' @param x a numeric vector of x coordinates
#' @param y a numeric vector of y coordinates
#' 
#' @return A numeric matrix
#' 
#' @export
#' @rdname polar2cartesian
cartesian2polar <- function(x, y) {
    .Call('_sccm_cartesian2polar', PACKAGE = 'sccm', x, y)
}

convex_hull_cpp <- function(x, y) {
    .Call('_sccm_convex_hull_cpp', PACKAGE = 'sccm', x, y)
}

is_in_cpp <- function(x, y, v) {
    .Call('_sccm_is_in_cpp', PACKAGE = 'sccm', x, y, v)
}

polygon_cpp <- function(x, y) {
    .Call('_sccm_polygon_cpp', PACKAGE = 'sccm', x, y)
}

