# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convex_hull_cpp <- function(x, y) {
    .Call('sccm_convex_hull_cpp', PACKAGE = 'sccm', x, y)
}

polygon_cpp <- function(x, y) {
    .Call('sccm_polygon_cpp', PACKAGE = 'sccm', x, y)
}

